// REFACTORED CODE (Generated by Gemini AI)
// Original file: D:\Major Project\testing_files\fetchdata.js
// Generated by Refactor Agent using Gemini
//
// Improvements made:
//   - Code refactored for improved quality using Gemini AI
//
// ============================================

const axios = require("axios");

const USERS_API_BASE_URL = "https://jsonplaceholder.typicode.com";
const TARGET_USER_ID = 1;

async function fetchUser() {
  try {
    const response = await axios.get(`${USERS_API_BASE_URL}/users/${TARGET_USER_ID}`);
    const userData = response.data;

    if (!userData || typeof userData.name !== 'string') {
      throw new Error("User data is incomplete or missing a valid name.");
    }

    return userData.name;
  } catch (error) {
    if (axios.isAxiosError(error)) {
      if (error.response) {
        throw new Error(`Failed to fetch user ${TARGET_USER_ID}: Server responded with status ${error.response.status}.`);
      }
      if (error.request) {
        throw new Error(`Failed to fetch user ${TARGET_USER_ID}: No response received from server.`);
      }
      throw new Error(`Failed to fetch user ${TARGET_USER_ID}: Request setup error - ${error.message}.`);
    }
    throw new Error(`An unexpected error occurred while fetching user ${TARGET_USER_ID}: ${error.message}.`);
  }
}

module.exports = { fetchUser };

// ============================================
// How to use this refactored code:
// 1. Review the changes above carefully
// 2. Test the refactored code thoroughly
// 3. Replace the original file: D:\Major Project\testing_files\fetchdata.js
// 4. Update any imports or references if needed
