// REFACTORED CODE (Generated by Gemini AI)
// Original file: D:\Major Project\testing_files\javascript.js
// Generated by Refactor Agent using Gemini
//
// Improvements made:
//   - Code refactored for improved quality using Gemini AI
//
// ============================================

const checkEvenOdd = (num) => {
    if (typeof num !== 'number' || !Number.isInteger(num)) {
        throw new TypeError('Input must be an integer number.');
    }
    return num % 2 === 0 ? "Even number" : "Odd number";
};

const findMax = (a, b) => {
    if (typeof a !== 'number' || typeof b !== 'number' || !Number.isFinite(a) || !Number.isFinite(b)) {
        throw new TypeError('Both inputs must be finite numbers.');
    }
    return a > b ? a : b;
};

const canVote = (age) => {
    if (typeof age !== 'number' || !Number.isInteger(age) || age < 0) {
        throw new RangeError('Age must be a non-negative integer.');
    }
    return age >= 18 ? "Eligible to vote" : "Not eligible to vote";
};

const calculateGrade = (marks) => {
    if (typeof marks !== 'number' || marks < 0 || marks > 100) {
        throw new RangeError('Marks must be a number between 0 and 100.');
    }

    if (marks >= 90) {
        return "A Grade";
    }
    if (marks >= 75) {
        return "B Grade";
    }
    if (marks >= 50) {
        return "C Grade";
    }
    return "Fail";
};

const loginStatus = (isLoggedIn) => {
    if (typeof isLoggedIn !== 'boolean') {
        throw new TypeError('Input must be a boolean value.');
    }
    return isLoggedIn ? "User is logged in" : "User is logged out";
};

// ============================================
// How to use this refactored code:
// 1. Review the changes above carefully
// 2. Test the refactored code thoroughly
// 3. Replace the original file: D:\Major Project\testing_files\javascript.js
// 4. Update any imports or references if needed
