# REFACTORED CODE (Generated by Gemini AI)
# Original file: D:\Major Project\testing_files\python1.py
# Generated by Refactor Agent using Gemini
#
# Improvements made:
#   - Code refactored for improved quality using Gemini AI
#
# ============================================

import math

def add(a: float, b: float) -> float:
    return a + b

def subtract(a: float, b: float) -> float:
    return a - b

def multiply(a: float, b: float) -> float:
    return a * b

def divide(a: float, b: float) -> float:
    if b == 0:
        raise ZeroDivisionError("Cannot divide by zero")
    return a / b

def is_even(n: int) -> bool:
    return n % 2 == 0

# ============================================
# How to use this refactored code:
# 1. Review the changes above carefully
# 2. Test the refactored code thoroughly
# 3. Replace the original file: D:\Major Project\testing_files\python1.py
# 4. Update any imports or references if needed
