# REFACTORED CODE (Generated by Gemini AI)
# Original file: D:\Major Project\testing_files\python3.py
# Generated by Refactor Agent using Gemini
#
# Improvements made:
#   - Code refactored for improved quality using Gemini AI
#
# ============================================

import requests
import json
from datetime import datetime
from statistics import mean, StatisticsError
from typing import Dict, List, Any, Optional, Union

class DataService:
    def __init__(self):
        self._session = requests.Session()

    def fetch_user(self, user_id: int) -> Optional[Dict[str, Any]]:
        url = f"https://jsonplaceholder.typicode.com/users/{user_id}"
        try:
            response = self._session.get(url)
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException:
            return None

    def get_user_email(self, user_data: Dict[str, Any]) -> Optional[str]:
        return user_data.get("email")

    def calculate_average_age(self, users: List[Dict[str, Any]]) -> Optional[float]:
        ages = [user["age"] for user in users if "age" in user and isinstance(user["age"], (int, float))]
        if not ages:
            return None
        try:
            return mean(ages)
        except StatisticsError:
            return None

    def parse_json_data(self, json_string: str) -> Optional[Union[Dict[str, Any], List[Any]]]:
        try:
            data = json.loads(json_string)
            if isinstance(data, dict) and "data" in data:
                return data["data"]
            return None
        except json.JSONDecodeError:
            return None

    def format_join_date(self, date_string: str) -> Optional[str]:
        try:
            date_obj = datetime.strptime(date_string, "%d-%m-%Y")
            return date_obj.strftime("%Y-%m-%d")
        except ValueError:
            return None

# ============================================
# How to use this refactored code:
# 1. Review the changes above carefully
# 2. Test the refactored code thoroughly
# 3. Replace the original file: D:\Major Project\testing_files\python3.py
# 4. Update any imports or references if needed
