# FIXED CODE for reverse_string
# Original file: D:\Major Project\testing_files\python.py
# Generated by Debug Agent

import re

def reverse_string(text):
    # The original implementation `text[::-1]` reverses Unicode code points.
    # This can lead to incorrect behavior for strings containing grapheme clusters
    # (e.g., multi-codepoint emojis like family emojis, or characters with combining diacritics).
    # The failing test likely includes such complex symbols.

    # To correctly reverse a string by its perceived characters (grapheme clusters),
    # we first split the string into a list of its grapheme clusters using `re.findall`
    # with the `\X` regex pattern, which matches a Unicode grapheme cluster.
    grapheme_clusters = re.findall(r'\X', text)
    
    # Then, we reverse the list of these clusters.
    reversed_clusters = grapheme_clusters[::-1]
    
    # Finally, we join the reversed clusters back into a single string.
    return "".join(reversed_clusters)

# How to apply this fix:
# 1. Copy the function above
# 2. Replace the original function in D:\Major Project\testing_files\python.py
# 3. Re-run tests to verify the fix
