# FIXED CODE for reverse_string
# Original file: D:\Major Project\testing_files\python.py
# Generated by Debug Agent

def reverse_string(text):
    if not isinstance(text, str):
        raise TypeError("Input must be a string.")
    return text[::-1]

# How to apply this fix:
# 1. Copy the function above
# 2. Replace the original function in D:\Major Project\testing_files\python.py
# 3. Re-run tests to verify the fix
