# FIXED CODE for calculate_square_root
# Original file: D:\Major Project\testing_files\python.py
# Generated by Debug Agent

import math

def calculate_square_root(number):
    if number < 0:
        raise ValueError("Cannot calculate square root of a negative number.")
    result = math.sqrt(number)
    return result

# How to apply this fix:
# 1. Copy the function above
# 2. Replace the original function in D:\Major Project\testing_files\python.py
# 3. Re-run tests to verify the fix
