# FIXED CODE for format_join_date
# Original file: D:\Major Project\testing_files\python3.py
# Generated by Debug Agent

import datetime

class MyClass: # Assuming the function is part of a class as indicated by 'self'
    def format_join_date(self, date_string):
        """
        Format date into YYYY-MM-DD
        """
        # Parse the date string.
        # This will raise ValueError for invalid date formats or values (e.g., "32-01-2023", "hello").
        # It will raise TypeError if date_string is not a string (e.g., None).
        date_obj = datetime.datetime.strptime(date_string, "%d-%m-%Y")

        # BUG FIX: Change the output format to YYYY-MM-DD as specified in the docstring.
        return date_obj.strftime("%Y-%m-%d")

# How to apply this fix:
# 1. Copy the function above
# 2. Replace the original function in D:\Major Project\testing_files\python3.py
# 3. Re-run tests to verify the fix
