# FIXED CODE for is_even
# Original file: D:\Major Project\testing_files\python1.py
# Generated by Debug Agent

def is_even(n):
    if isinstance(n, float):
        raise TypeError("is_even only supports integer types, not floats.")
    if n % 2 == 0:
        return True

# How to apply this fix:
# 1. Copy the function above
# 2. Replace the original function in D:\Major Project\testing_files\python1.py
# 3. Re-run tests to verify the fix
