# FIXED CODE for fetch_user
# Original file: D:\Major Project\testing_files\python3.py
# Generated by Debug Agent

import requests
from requests.exceptions import RequestException, HTTPError, JSONDecodeError

class UserFetcher: # Assuming the function is part of a class based on 'self'

    def fetch_user(self, user_id):
        """
        Fetch user data from API
        """
        url = f"https://jsonplaceholder.typicode.com/users/{user_id}"
        try:
            # Add a timeout for robustness against hanging requests
            response = requests.get(url, timeout=5)

            # Check for HTTP status codes indicating an error (4xx or 5xx)
            # This raises an HTTPError for non-2xx responses.
            response.raise_for_status()

            # If status is 200-299, attempt to parse JSON
            return response.json()

        except HTTPError as e:
            # Handles 404 Not Found, 400 Bad Request, 500 Internal Server Error, etc.
            # As per test expectations, return empty JSON for all these cases.
            # This addresses test_fetch_user_not_found_returns_empty_json
            # and contributes to test_fetch_user_api_error_invalid_json_response
            return {}
        except JSONDecodeError:
            # This catches cases where the status code was 2xx (successful)
            # but the response body was not valid JSON (e.g., empty body, HTML).
            # This directly addresses part of test_fetch_user_api_error_invalid_json_response
            return {}
        except RequestException:
            # This is a broad catch for all other requests-related errors:
            # ConnectionError, Timeout, TooManyRedirects, etc.
            # This addresses test_fetch_user_network_error
            return {}

# How to apply this fix:
# 1. Copy the function above
# 2. Replace the original function in D:\Major Project\testing_files\python3.py
# 3. Re-run tests to verify the fix
