# FIXED CODE for format_join_date
# Original file: D:\Major Project\testing_files\python4.py
# Generated by Debug Agent

from datetime import datetime

class SomeClass: # Assuming the function is part of a class based on 'self'
    def format_join_date(self, date_string):
        """
        Format date into YYYY-MM-DD
        """
        try:
            date_obj = datetime.strptime(date_string, "%d-%m-%Y")
            return date_obj.strftime("%Y-%m-%d")
        except (ValueError, TypeError):
            # This block handles:
            # 1. TypeError: If 'date_string' is not a string (e.g., an integer),
            #    which addresses 'test_format_join_date_non_string_input_int'.
            # 2. ValueError: If 'date_string' is a string but does not match
            #    the "%d-%m-%Y" format or represents a non-existent date,
            #    which addresses 'test_format_join_date_invalid_date_non_existent'.
            return None

# How to apply this fix:
# 1. Copy the function above
# 2. Replace the original function in D:\Major Project\testing_files\python4.py
# 3. Re-run tests to verify the fix
