# FIXED CODE for calculate_square_root
# Original file: D:\Major Project\testing_files\python.py
# Generated by Debug Agent

import math

def calculate_square_root(number):
    # Ensure a ValueError is explicitly raised for negative inputs,
    # potentially with a more specific message expected by tests.
    if number < 0:
        raise ValueError("Input must be a non-negative number.")
    
    # The math.sqrt function handles valid non-negative numbers.
    # It also correctly raises TypeError for non-numeric inputs,
    # which aligns with test_calculate_square_root_non_numeric_input_raises_type_error passing.
    result = math.sqrt(number)
    return result

# How to apply this fix:
# 1. Copy the function above
# 2. Replace the original function in D:\Major Project\testing_files\python.py
# 3. Re-run tests to verify the fix
